---
  - name: Fact Finder
    hosts: csr
    tasks:
      - name: Register Ansible Facts
        setup:
        register: anisble_facts
      - name: Print Ansible Facts
        debug: 
          msg: "{{ ansible_facts }}"
