---
  - name: Woohoo! Configuration Time!
    gather_facts: no
    hosts: csr
    vars:
      credentials:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
    tasks:
      - name: Build me an ACL!!
        ios_config:
          provider: "{{ credentials }}"
          lines: 
            - permit ip host 1.1.1.1 host 8.8.8.8 log
            - permit ip host 1.1.1.2 host 8.8.8.8 log
            - permit ip host 1.1.1.3 host 8.8.8.8 log
          parents: ip access-list extended AnsibleACL
